name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: CI
        run: |
          make ci
